language: node_js
node_js:
  - "stable"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ui
  on:
    branch: master

notifications:
  email: false
  slack:
    on_success: never
dist: trusty

addons:
  postgresql: "9.4"
  chrome: stable
  code_climate:
    repo_token: $CLIMATE_CODE_REPORTER

#services:
#  - postgresql

before_script:
      - psql -c 'create database mydiary_test;' -U postgres
      - npm install codeclimate-test-reporter -g
      - mv .env.sample .env

after_success:
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info

