language: node_js
node_js:
  - "stable"
addons:
  chrome: stable
  code_climate:
    repo_token: $CLIMATE_CODE_REPORTER
  postgresql: "9.4"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ui
  on:
    branch: master

dist: trusty

env:
  global:
  - PGPORT=5433
  - DB_URL=postgres://postgres:@localhost:5432/travis_ci_test

notifications:
  email: false
  slack:
    on_success: never
services:
  - postgresql

before_script:
      - npm install codeclimate-test-reporter -g
      - mv .env.sample .env
      - psql -c 'create database travis_ci_test;' -U postgres

after_success:
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info
