language: node_js
node_js:
  - "stable"

env:
  - DB_URL=postgres://postgres:oreoluwa@localhost:5432/mydiary_test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ui
  on:
    branch: develop

notifications:
  email: false
  slack:
    on_success: never
dist: trusty

addons:
  postgresql: "9.4"
  chrome: stable
  code_climate:
    repo_token: $CLIMATE_CODE_REPORTER

#services:
#  - postgresql
before_script:
      - psql -c 'create database mydiary_test;' -U postgres
      - npm install codeclimate-test-reporter -g
      - npm install -g sonarqube-scanner
      - npm run webpack:prod
      - mv .env.sample .env
      - mv sonar-project.properties.sample sonar-project.properties
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - npm run coverage